1.	scrape_configs:
2.	- job_name: 'federate'
3.	scrape_interval: 1m
4.	honor_labels: true
5.	metrics_path: '/federate'
6.	params:
7.	'match[]':
8.	- '{job="kubernetes-pods"}'
9.	static_configs:
10.	- targets:
11.	- 'prometheus-server-1:9090'
12.	- 'prometheus-server-2:9090'

